name: allure-update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Allure history from S3
        run: |
          aws s3 cp s3://${{ secrets.S3_BUCKET }}/history/ allure-results/history/ \
            --recursive || echo "No history found, starting fresh"

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Debug allure-results
        run: ls -la allure-results/ && ls -la allure-results/history/ || echo "Pastas vazias ou inexistentes"

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report to S3
        run: |
          aws s3 sync allure-report/ s3://${{ secrets.S3_BUCKET }}/ \
            --delete \
            --cache-control "no-cache"
